name: push-to-master
on:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: test-${{ matrix.os }}
    steps:
      - name: Setup Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        env:
          GOPATH: ${{ runner.workspace }}
          GOBIN: ${{ runner.workspace }}/bin
      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          path: src/github.com/${{ github.repository }}
      - name: Setup Go Environment
        run: |
          mkdir -p $GOPATH/bin
        shell: bash
      - name: Get Dependencies
        run: |
          cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          $GOBIN/dep ensure
        shell: bash
      - name: Run Tests
        run: |
          cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
          go test ./tests/...
        shell: bash
